
{{- range $key, $value := .Values.sealedSecrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $key }}
  namespace: {{ $.Release.Namespace }}
spec:
  encryptedData:
{{ $value | toYaml | indent 4 }}
  template:
    metadata:
      creationTimestamp: null
      name: {{ $key }}
      namespace: {{ $.Release.Namespace }}
    type: Opaque
---

{{- end }}